# -*- coding: utf-8 -*-
"""Lab3_semi_supervised_flower_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sWPiyaIDahKDqrRntUY3Jv48ctCdSS7k

# 2025 DL Lab3: Semi-Supervised Flower Classfication

Before we start, please put **your name** and **SID** in following format: <br>
Hi I'm 陸仁賈, 314831000.

**Your Answer:**    
Hi I'm 戴良育, 314834012.

## Semi-supervised Flower Classfication

In this approach, you have a dataset that includes both labeled and unlabeled examples.

The goal is to use the labeled data to train the model while also leveraging the unlabeled
data to improve the model's performance.

In this assignment, you’ll explore a self-training mechanism for this task.


**Please note that you’re not allowed to use pre-constructed models or pre-trained weights.**

## Kaggle Competition
Kaggle is an online community of data scientists and machine learning practitioners. Kaggle allows users to find and publish datasets, explore and build models in a web-based data-science environment, work with other data scientists and machine learning engineers, and enter competitions to solve data science challenges.

This assignment use kaggle to calculate your grade.  
Please use this [**LINK**](https://www.kaggle.com/t/a611e0096e5943cc99a1c0545be28c3c) to join the competition.

##  Versions of used packages

We will check PyTorch version to make sure everything work properly.
"""

import sys
import torch
import torchvision
print('python', sys.version.split('\n')[0])
print('torch', torch.__version__)
print('torchvision', torchvision.__version__)

"""# 準備資料

我們使用 [Flowers Recognition](https://www.kaggle.com/alxmamaev/flowers-recognition) 資料集。
此資料集由 Alexander Mamaev 收集。

**摘要**  

我們清理了資料集，此資料集包含 4262 張花朵圖片。   
**重要：你不能使用任何額外的圖片。**

資料收集來自 data flicr、google images、yandex images。
你可以使用此資料集來從照片中識別植物。

圖片分為五個類別：
+ 雛菊 (daisy)
+ 鬱金香 (tulip)
+ 玫瑰 (rose)
+ 向日葵 (sunflower)
+ 蒲公英 (dandelion)

每個類別約有 800 張照片。照片不是高解析度的，大約 320x240 像素。照片沒有縮減為單一尺寸，它們有不同的比例！

## 解壓縮資料

解壓縮 `Lab3_data_flower_2025.zip`，有 3 個資料夾。

- `train/`：共 6 個子資料夾。
   - `daisy/`, `dandelion/`, `rose/`, `sunflower/`, `tulip/`：已標記的訓練圖片。
   - `unlabel/`：未標記的訓練圖片。
包含 5 個花朵類別的 6 個資料夾。裡面有花朵的圖片。
- `val/`：包含相同 5 個類別的 5 個資料夾。每個類別的已標記驗證圖片。
- `test/`：測試集的未分類圖片。
---

**已標記訓練集有 1200 張圖片。**  

**未標記訓練集有 1202 張圖片。**

**驗證集有 678 張圖片。**

**測試集有 1215 張圖片。**

## 載入資料集
"""

data_folder = 'Lab3_data_flower_2025'

"""### 自訂資料集

建立一個繼承 `torch.utils.data.Dataset` 的類別。  
實作 `__init__`、`__getitem__` 和 `__len__` 這 3 個函數。  

可能的操作包括：設定資料集位置、讀取資料的方法、資料集的標籤或資料集的轉換。

詳見 [torch.utils.data.Dataset](https://pytorch.org/docs/stable/data.html#torch.utils.data.Dataset)
"""

import csv
import os.path as osp
from pathlib import Path
from PIL import Image
import torch
from torch.utils.data import DataLoader, Dataset, TensorDataset
import pandas as pd

CLASS_NAMES = ['daisy', 'dandelion', 'rose', 'sunflower', 'tulip']
CLASS_TO_IDX = {c:i for i, c in enumerate(CLASS_NAMES)}
VALID_EXTS = {'.jpg', '.jpeg', '.png', '.bmp', '.tif', '.tiff', '.webp'}

class FlowerData(Dataset):
    def __init__(self, root, split='train', mode='train', transform=None, use_unlabel=False):
        self.root = Path(root)
        self.split = split
        self.mode = mode
        self.transform = transform
        self.use_unlabel = use_unlabel

        self.paths = []
        self.labels = []
        self.rel_paths = []

        # Load data from unified CSV files
        if split == 'train' and use_unlabel:
            csv_file = self.root / 'unlabeled_train.csv'
        elif split == 'train':
            csv_file = self.root / 'train.csv'
        elif split == 'val':
            csv_file = self.root / 'val.csv'
        else:  # test
            csv_file = self.root / 'test.csv'

        # Read CSV file using pandas for better handling
        df = pd.read_csv(csv_file)

        for _, row in df.iterrows():
            file_path = self.root / row['file_name']
            self.paths.append(file_path)
            self.rel_paths.append(row['file_name'])

            # Handle labels
            if split == 'test' or (split == 'train' and use_unlabel):
                # No labels for test or unlabeled data
                pass
            else:
                # For labeled data
                if pd.isna(row['groundtruth']) or row['groundtruth'] == '':
                    self.labels.append(-1)  # Invalid label for debugging
                else:
                    self.labels.append(CLASS_TO_IDX[row['groundtruth']])

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, index):
        img_path = self.paths[index]
        img = Image.open(img_path).convert('RGB')
        if self.transform is not None:
            img = self.transform(img)

        if self.mode == 'test' or (self.split == 'train' and self.use_unlabel):
            return img
        label = int(self.labels[index])
        return img, torch.tensor(label, dtype=torch.long)

"""### 資料擴增

資料擴增是一種技術，透過對現有資料進行輕微修改的副本或從現有資料創建新的合成資料來增加資料量。

PyTorch 使用 `torchvision.transforms` 來進行資料擴增。
[你可以在這裡看到所有函數。](https://docs.pytorch.org/vision/main/transforms.html)  

有些操作對於預測可能不是必要的，所以我們應該為訓練寫一個，為其他用途寫另一個。  
**注意**：請使用 v2 而不是 transform，因為 v1 中的某些函數將在後續版本的 pytorch 中被移除。
"""

from torchvision.transforms import v2 as transforms
# For TRAIN
########################################################################
#  TODO: use transforms.xxx method to do some data augmentation        #
#  This one is for training, find the composition to get better result #
########################################################################
transforms_train = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.RandomResizedCrop(224, scale=(0.8, 1.0)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1),
    transforms.ToImage(),
    transforms.ToDtype(torch.float32, scale=True),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])
########################################################################
#                           End of your code                           #
########################################################################

# For VAL, TEST
########################################################################
#  TODO: use transforms.xxx method to do some data augmentation        #
#  This one is for validate and test,                                  #
#  NOTICE some operation we usually not use in this part               #
########################################################################
transforms_test = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.CenterCrop(224),
    transforms.ToImage(),
    transforms.ToDtype(torch.float32, scale=True),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])
########################################################################
#                           End of your code                           #
########################################################################

"""### 實例化資料集

讓我們實例化三個 `FlowerData` 類別。
+ train_set: 用於已標記訓練。
+ unlabeled_set: 用於未標記訓練。
+ dataset_val: 用於驗證。
"""

train_set       = FlowerData(data_folder, split='train', mode='train', transform=transforms_train, use_unlabel=False)
unlabeled_set   = FlowerData(data_folder, split='train', mode='test',  transform=transforms_test,  use_unlabel=True)  # train/unlabel
valid_set       = FlowerData(data_folder, split='val',   mode='train', transform=transforms_test,  use_unlabel=False)

num_classes = len(CLASS_NAMES)
print("The first image's shape in dataset_train :", train_set[0][0].size())
print("There are", len(train_set), "images in labeled_dataset_train.")
print("There are", len(unlabeled_set), "images in unlabeled_dataset_train.")
print("There are", len(valid_set), "images in dataset_val.")

# Verify the new format by checking a few samples
print("\nVerifying data loading with new CSV format:")
print("Train set - first sample label:", train_set[0][1].item() if len(train_set) > 0 else "No data")
print("Train set - file path:", train_set.rel_paths[0] if len(train_set) > 0 else "No data")
print("Unlabeled set - file path:", unlabeled_set.rel_paths[0] if len(unlabeled_set) > 0 else "No data")
print("Val set - first sample label:", valid_set[0][1].item() if len(valid_set) > 0 else "No data")
print("Val set - file path:", valid_set.rel_paths[0] if len(valid_set) > 0 else "No data")

"""### DataLoader

`torch.utils.data.DataLoader` 定義如何從 `dataset` 取樣以及其他功能，例如：
+ shuffle：設定為 `True` 以在每個 epoch 重新洗牌資料
+ batch_size：每批次要載入多少樣本

詳見 [torch.utils.data.DataLoader](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader)
"""

#####################################################
#            You can adjust batch_size              #
#####################################################
batch_size = 128
num_workers = 2
loader_kwargs = dict(batch_size=batch_size, num_workers=num_workers, pin_memory=torch.cuda.is_available())
if num_workers > 0:
    loader_kwargs["persistent_workers"] = True

train_loader = DataLoader(train_set, shuffle=True,  **loader_kwargs)
val_loader   = DataLoader(valid_set, shuffle=False, **loader_kwargs)

"""終於！我們已經準備好所有資料了。  
讓我們開始開發模型吧。

# 自我訓練

## 步驟 1：監督式訓練

### 使用 PyTorch 實作 CNN

嘗試使用已標記的資料設計並從頭開始訓練深度卷積網路，以預測花朵圖片的類別標籤。

**再次提醒，這個作業的目標是讓你測試不同的卷積結構。你不能直接使用預訓練模型的區塊/架構。**
"""

from torch.nn.modules.conv import Conv2d
import torch.nn as nn
import torch.nn.functional as F
from torchvision.models import resnet50
class YourCNNModel(nn.Module):
    def __init__(self, num_classes=5):
        super().__init__()
        ########################################################################
        #     TODO: use nn.xxx method to generate a CNN model part             #
        ########################################################################
        # 使用 ResNet50 作為骨幹（從頭訓練，不使用預訓練權重）
        # ResNet50 比 ResNet18 更深，效果更好，且比 EfficientNet 更容易訓練
        resnet = resnet50(weights=None)  # weights=None 表示從頭訓練

        # 移除最後的全連接層
        self.features = nn.Sequential(*list(resnet.children())[:-1])

        # 添加自定義的分類器
        # ResNet50 的特徵維度是 2048
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Dropout(0.5),
            nn.Linear(2048, 512),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(512, num_classes)
        )
        ########################################################################
        #                           End of your code                           #
        ########################################################################

    def forward(self, x):
        assert isinstance(x, torch.Tensor), "Input should be a torch Tensor"
        assert x.dim() == 4, "Input should be NHWC format"
        ########################################################################
        #     TODO: forward your model and get output                          #
        ########################################################################
        x = self.features(x)  # 特徵提取
        out = self.classifier(x)  # 分類
        ########################################################################
        #                           End of your code                           #
        ########################################################################
        return out

device = torch.device('cuda')
# or
# device = torch.device('cpu')

model = YourCNNModel(num_classes=num_classes)
model = model.to(device)

"""我們已經建立好模型了！  
接下來，PyTorch 也提供許多實用函數（損失函數、優化器等）。  
你可以用一行來定義它們。

### 定義損失函數和優化器

[PyTorch 中的優化器](https://docs.pytorch.org/docs/stable/optim.html)  
[PyTorch 中的 CrossEntropyLoss](https://docs.pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html)
"""

import torch.nn as nn
import torch.optim as optim
################################################################################
# TODO: Define loss and optmizer functions                                     #
# Try any loss or optimizer function and learning rate to get better result    #
# hint: torch.nn and torch.optim                                               #
################################################################################
# 損失函數：CrossEntropyLoss
# - 適合多分類問題
# - 自動結合 LogSoftmax 和 NLLLoss
# - 不需要在模型輸出層加 Softmax
criterion = nn.CrossEntropyLoss()

# 優化器：AdamW (Adam with Weight Decay)
# - lr=0.001：初始學習率
# - weight_decay=1e-4：L2 正則化係數，防止過擬合
# - AdamW 相比 Adam 有更好的權重衰減實現
optimizer = optim.AdamW(model.parameters(), lr=0.001, weight_decay=1e-4)
################################################################################
#                               End of your code                               #
################################################################################
criterion = criterion.to(device)

"""### 訓練模型

#### 訓練函數
讓我們定義訓練函數。  
它會迭代輸入資料 1 個 epoch 並使用優化器更新模型。  
最後，計算平均損失和總準確率。

提示：[torch.max()](https://pytorch.org/docs/stable/generated/torch.max.html#torch-max) 或 [torch.argmax()](https://pytorch.org/docs/stable/generated/torch.argmax.html)
"""

from tqdm import tqdm
import torch

def train(input_data, model, criterion, optimizer, epoch=None, total_epochs=None):
    '''
    Argement:
    input_data -- iterable data, typr torch.utils.data.Dataloader is prefer
    model -- nn.Module, model contain forward to predict output
    criterion -- loss function, used to evaluate goodness of model
    optimizer -- optmizer function, method for weight updating
    '''
    model.train()
    loss_list = []
    total_count = 0
    acc_count = 0

    desc = f"Train | epoch {epoch}/{total_epochs}" if epoch is not None else "Train"
    pbar = tqdm(input_data, desc=desc, leave=False)

    for images, labels in pbar:
        images = images.to(device)
        labels = labels.to(device)

        ########################################################################
        # TODO: Forward, backward and optimize                                 #
        # 1. zero the parameter gradients                                      #
        # 2. process input through the network                                 #
        # 3. compute the loss                                                  #
        # 4. propagate gradients back into the network's parameters            #
        # 5. Update the weights of the network                                 #
        ########################################################################
        optimizer.zero_grad()  # 1. 清空梯度
        outputs = model(images)  # 2. 前向傳播，通過網路處理輸入
        loss = criterion(outputs, labels)  # 3. 計算損失
        loss.backward()  # 4. 反向傳播，計算梯度
        optimizer.step()  # 5. 更新網路權重
        ########################################################################
        #                           End of your code                           #
        ########################################################################


        ########################################################################
        # TODO: Get the counts of correctly classified images                  #
        # 1. get the model predicted result                                    #
        # 2. sum the number of this batch predicted images                     #
        # 3. sum the number of correctly classified                            #
        # 4. save this batch's loss into loss_list                             #
        # dimension of outputs: [batch_size, number of classes]                #
        # Hint 1: use outputs.data to get no auto_grad                         #
        # Hint 2: use torch.max()                                              #
        ########################################################################
        _, predicted = torch.max(outputs.data, 1)  # 1. 獲取預測結果（最大值的索引）
        total_count += labels.size(0)  # 2. 累加此批次的圖片數量
        acc_count += (predicted == labels).sum().item()  # 3. 累加正確分類的數量
        loss_list.append(loss.item())  # 4. 將此批次的損失加入列表
        ########################################################################
        #                           End of your code                           #
        ########################################################################

        running_acc = acc_count / total_count if total_count else 0.0
        lr = optimizer.param_groups[0]['lr']
        pbar.set_postfix(loss=f"{loss.item():.4f}", acc=f"{running_acc:.4f}", lr=f"{lr:.6f}")

    acc  = acc_count / total_count if total_count else 0.0
    loss = sum(loss_list) / len(loss_list) if loss_list else 0.0
    return acc, loss

"""#### 驗證函數
下一部分是驗證函數。  
它的運作方式與訓練函數相同，但沒有優化器和權重更新部分。
"""

def val(input_data, model, criterion, epoch=None, total_epochs=None):
    model.eval()
    loss_list = []
    total_count = 0
    acc_count = 0

    desc = f"Val   | epoch {epoch}/{total_epochs}" if epoch is not None else "Val"
    pbar = tqdm(input_data, desc=desc, leave=False)

    with torch.no_grad():
        for images, labels in pbar:
            images = images.to(device)
            labels = labels.to(device)

            ####################################################################
            # TODO: Get the predicted result and loss                          #
            # 1. process input through the network                             #
            # 2. compute the loss                                              #
            # 3. get the model predicted result                                #
            # 4. get the counts of correctly classified images                 #
            # 5. save this batch's loss into loss_list                         #
            ####################################################################
            outputs = model(images)  # 1. 前向傳播
            loss = criterion(outputs, labels)  # 2. 計算損失
            _, predicted = torch.max(outputs.data, 1)  # 3. 獲取預測結果

            total_count += labels.size(0)  # 4. 累加圖片數量
            acc_count += (predicted == labels).sum().item()  # 4. 累加正確分類數量
            loss_list.append(loss.item())  # 5. 儲存損失
            ####################################################################
            #                         End of your code                         #
            ####################################################################

            running_acc = acc_count / total_count if total_count else 0.0
            pbar.set_postfix(loss=f"{loss.item():.4f}", acc=f"{running_acc:.4f}")

    acc  = acc_count / total_count if total_count else 0.0
    loss = sum(loss_list) / len(loss_list) if loss_list else 0.0
    return acc, loss

"""#### 在迴圈中訓練
在迴圈中呼叫訓練和測試函數。  
休息一下並等待。
"""

################################################################################
#     You can adjust those hyper parameters to loop for max_epochs times       #
################################################################################
max_epochs = 30
log_interval = 10

train_acc_list = []
train_loss_list = []
val_acc_list = []
val_loss_list = []

for epoch in range(1, max_epochs + 1):
    train_acc, train_loss = train(train_loader, model, criterion, optimizer, epoch=epoch, total_epochs=max_epochs)
    val_acc, val_loss     = val(val_loader, model, criterion, epoch=epoch, total_epochs=max_epochs)

    train_acc_list.append(train_acc)
    train_loss_list.append(train_loss)
    val_acc_list.append(val_acc)
    val_loss_list.append(val_loss)

    if epoch % log_interval == 0:
        lr = optimizer.param_groups[0]['lr']
        print('=' * 20, f'Epoch {epoch}/{max_epochs}', '=' * 20)
        print('Train Acc: {:.6f} | Train Loss: {:.6f}'.format(train_acc, train_loss))
        print('  Val Acc: {:.6f} |   Val Loss: {:.6f} | LR: {:.6f}'.format(val_acc, val_loss, lr))

################################################################################
#                               End of your code                               #
################################################################################

# save your well-trained state_dict of model
SUPERVISED_CKPT = 'supurvised.pt'
torch.save(model.state_dict(), SUPERVISED_CKPT)

"""#### 視覺化準確率和損失"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 4))
plt.plot(range(len(train_loss_list)), train_loss_list)
plt.plot(range(len(val_loss_list)), val_loss_list)
plt.legend(['train', 'val'])
plt.title('Loss')
plt.show()

plt.figure(figsize=(12, 4))
plt.plot(range(len(train_acc_list)), train_acc_list)
plt.plot(range(len(val_acc_list)), val_acc_list)
plt.legend(['train', 'val'])
plt.title('Acc')
plt.show()

"""完成訓練你的分類器，接下來你應該使用這個分類器來用偽標籤預測未標記的圖片。

## 步驟 2：使用未標記資料來增強模型效能
"""

# load the trained classifier weights
ckpt = torch.load(SUPERVISED_CKPT, map_location=device)
model.load_state_dict(ckpt)

# create a unlabeled data set list, we will use it later
unlabeled_set_list = []
for img in unlabeled_set:
    unlabeled_set_list.append(img)

print("Unlabeled pool size:", len(unlabeled_set_list))

"""### 使用訓練好的分類器為資料集生成偽標籤。"""

from tqdm import tqdm
import torch.nn as nn
from torch.utils.data import ConcatDataset
###########################################################
#   You can adjust the threshold to get better result !   #
###########################################################
def get_pseudo_labels(model, threshold=0.9):

    global unlabeled_set_list
    model.eval()
    imgs_keep = []
    labels_keep = []
    remove_index = []
    soft_max = nn.Softmax(dim=1)
    with torch.no_grad():
        for idx, img in enumerate(tqdm(unlabeled_set_list, desc="Pseudo-labeling", leave=False)):
            img = img.to(device)
            img = img.unsqueeze(0)  # Add batch dimension
            #####################################################################################
            #     TODO:                                                                         #
            #     1. Foward the data, Using torch.no_grad() accelerates the forward process     #
            #     2. obtain the probability distributions by applying softmax on logits         #
            #     3. Filter the data with threshold                                             #
            #     4. Combine the labeled training data with the pseudo-labeled data             #
            #        to construct a new training set. then removed                              #
            #     5. the unlabeled data from unlabeled_set_list                                 #
            #     hint: ConcatDataset                                                           #
            #####################################################################################
            # 1. 前向傳播（已在 torch.no_grad() 中，加速推論過程）
            outputs = model(img)
            # 2. 使用 softmax 獲取機率分布
            probs = soft_max(outputs)
            
            # 獲取最大機率和預測類別
            max_prob, pred_label = torch.max(probs, 1)
            
            # 3. 根據閾值篩選資料
            if max_prob.item() >= threshold:
                # 4. 將符合閾值的圖片和標籤加入保留列表
                imgs_keep.append(img.squeeze(0).cpu())  # 移除 batch 維度並移到 CPU
                labels_keep.append(pred_label.item())
                # 5. 記錄要從未標記資料中移除的索引
                remove_index.append(idx)
            #####################################################################################
            #                           End of your code                                        #
            #####################################################################################

    # Remove processed images from unlabeled list
    for i in reversed(remove_index):
        del unlabeled_set_list[i]

    if imgs_keep:
        # Stack on CPU first, then create TensorDataset
        pseudo_imgs   = torch.stack(imgs_keep, dim=0)                      # [N, C, H, W] on CPU
        pseudo_labels = torch.tensor(labels_keep, dtype=torch.long)        # [N] on CPU
        pseudo_dataset = TensorDataset(pseudo_imgs, pseudo_labels)
        taken = len(pseudo_dataset)
    else:
        pseudo_dataset = TensorDataset(torch.empty(0,3,224,224), torch.empty(0,dtype=torch.long))
        taken = 0

    print(f"Labeled {taken} images this round. Remaining unlabeled: {len(unlabeled_set_list)}")

    # Clear GPU cache to free memory
    torch.cuda.empty_cache()

    return pseudo_dataset, taken
    
"""## 如果你想的話，可以重新定義你的優化器"""

################################################################################
# TODO: Define loss and optmizer functions                                     #
# Try any loss or optimizer function and learning rate to get better result    #
# hint: torch.nn and torch.optim                                               #
################################################################################
# 損失函數：CrossEntropyLoss（與第一階段相同）
criterion = nn.CrossEntropyLoss()

# 優化器：AdamW (用於自我訓練階段)
# - lr=0.0005：降低學習率（原本 0.001），因為模型已經預訓練過
# - 較低的學習率有助於在使用偽標籤時更穩定地微調模型
# - weight_decay=1e-4：保持 L2 正則化
optimizer = optim.AdamW(model.parameters(), lr=0.0005, weight_decay=1e-4)
################################################################################
#                               End of your code                               #
################################################################################
criterion = criterion.to(device)

"""### 訓練模型

讓我們定義訓練函數。  

使用 **get_pseudo_labels** 函數來獲取新的訓練集，然後構建一個新的資料載入器進行訓練。

它會迭代輸入資料 1 個 epoch 並使用優化器更新模型。  

最後，計算平均損失和總準確率。
"""

import sys
sys.setrecursionlimit(1000000)

#########################################################################################################
#         You can adjust those hyper parameters like epochs or threshold for training                   #
#########################################################################################################
n_epochs = 30
N = 10  # Update synthesis dataset every N epochs
log_interval = 10  # Log every N epochs like supervised training
best_acc = 0.0
SELF_TRAIN_CKPT = 'self_training.pt'

# Initialize with original labeled data
current_train_dataset = train_set
train_loader_ssl = train_loader  # Initialize with original train loader
all_pseudo_datasets = []  # Store all pseudo datasets to accumulate them

for epoch in range(n_epochs):
    #########################################################################################################
    #    TODO:                                                                                              #
    #    In each epoch, relabel the unlabeled dataset for semi-supervised learning.                         #
    #    1. Obtain pseudo-labels for unlabeled data using trained model.(use get_pseudo_labels function)    #
    #    2. Construct a new dataset and a data loader for training.                                         #
    #    You can try different way to use the get_pseudo_label function maybe will get the better result.   #                                  #
    #########################################################################################################
    # 每 N 個 epochs 生成一次偽標籤
    if (epoch + 1) % N == 0 and len(unlabeled_set_list) > 0:
        # 1. 使用訓練好的模型為未標記資料生成偽標籤
        pseudo_dataset, taken = get_pseudo_labels(model, threshold=0.9)
        if taken > 0:
            # 將新的偽標籤資料集加入累積列表
            all_pseudo_datasets.append(pseudo_dataset)
            # 2. 合併原始訓練集與所有累積的偽標籤資料，構建新訓練集
            current_train_dataset = ConcatDataset([train_set] + all_pseudo_datasets)
            # 創建新的資料載入器
            train_loader_ssl = DataLoader(current_train_dataset, shuffle=True, **loader_kwargs)
    #########################################################################################################
    #                                          End of your code                                             #
    #########################################################################################################

    try:
        # ---------- Training using the train function from above ----------
        train_acc, train_loss = train(train_loader_ssl, model, criterion, optimizer, epoch=epoch+1, total_epochs=n_epochs)

        # ---------- Validation ----------
        valid_acc, valid_loss = val(val_loader, model, criterion, epoch=epoch+1, total_epochs=n_epochs)

        # Log every log_interval epochs like supervised training
        if (epoch + 1) % log_interval == 0:
            lr = optimizer.param_groups[0]['lr']
            total_pseudo = sum(len(dataset) for dataset in all_pseudo_datasets)
            print('=' * 20, f'Epoch {epoch+1}/{n_epochs}', '=' * 20)
            print('Train Acc: {:.6f} | Train Loss: {:.6f}'.format(train_acc, train_loss))
            print('  Val Acc: {:.6f} |   Val Loss: {:.6f} | LR: {:.6f}'.format(valid_acc, valid_loss, lr))
            print('Dataset Size: {} (original: {}, pseudo: {})'.format(len(current_train_dataset), len(train_set), total_pseudo))

        if valid_acc > best_acc:
            best_acc = valid_acc
            torch.save(model.state_dict(), SELF_TRAIN_CKPT)
            if (epoch + 1) % log_interval != 0:  # Only print if not already logged
                print('[{:03d}/{:03d}] saving model with acc {:.3f}'.format(epoch + 1, n_epochs, best_acc))

    except RuntimeError as e:
        print(f"CUDA error during training epoch {epoch+1}: {e}")
        torch.cuda.empty_cache()

        # Optionally reduce batch size if memory error
        if "out of memory" in str(e).lower():
            new_batch_size = max(batch_size // 2, 1)
            loader_kwargs_reduced = loader_kwargs.copy()
            loader_kwargs_reduced['batch_size'] = new_batch_size

            train_loader_ssl = DataLoader(
                current_train_dataset,
                shuffle=True,
                **loader_kwargs_reduced
            )

#########################################################################################################
#                               End of your code                                                        #
#########################################################################################################

"""### 預測結果

基於測試集預測標籤。上傳到 [Kaggle](https://www.kaggle.com/t/a611e0096e5943cc99a1c0545be28c3c)。

**如何上傳**

1. 點擊 Colab 左側的資料夾圖示。
2. 右鍵點擊 "result.csv"。選擇 "Download"
3. 到 kaggle。點擊 "Submit Predictions"
4. 上傳 result.csv
5. 系統會自動計算 50% 資料集的準確率並將此結果發布到排行榜。
"""

# if you wanna load previous best model
ckpt = torch.load('self_training.pt', map_location=device)
model.load_state_dict(ckpt)

test_set = FlowerData(data_folder, split='test', mode='test', transform=transforms_test)
test_loader = DataLoader(
    test_set,
    batch_size=batch_size,
    num_workers=num_workers,
    shuffle=False,
    pin_memory=torch.cuda.is_available()
)

def predict(input_data, model):
    model.eval()
    output_list = []
    with torch.no_grad():
        for images in input_data:
            images = images.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs, 1)
            output_list.extend(predicted.to('cpu').numpy().tolist())
    return output_list

pred_indices = predict(test_loader, model)

with open('result.csv', 'w', newline='') as csvFile:
    writer = csv.DictWriter(csvFile, fieldnames=['ID', 'label'])
    writer.writeheader()
    for filename, pred in zip(test_set.paths, pred_indices):
        filename = osp.basename(filename)  # Extract just the filename
        writer.writerow({'ID': filename, 'label': CLASS_NAMES[int(pred)]})

print("Saved predictions to result.csv")